TweetApp/TweetApp/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name = 'userapp/login.html') , name = 'home'),
    url(r'^accounts/login/' , include('userapp.urls'), name = 'home'),
    url(r'^post/', include('postapp.urls')),
    url(r'^comment/', include('commentapp.urls')),
    url(r'^userapp/', include('userapp.urls')),
]

TweetApp/commentapp/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from .views import ListCommentByUser
from django.contrib.auth.decorators import login_required

app_name = 'commentapp'

urlpatterns = [
    url(r'^$', ListCommentByUser.as_view() , name = 'postComment'),
  
]

TweetApp/postapp/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from postapp.views import TweetList,TweetPost, TweetDetail

app_name = 'postapp'

urlpatterns = [
    url(r'^$', TweetList.as_view() , name = 'showTweet'),
    url(r'^post$', TweetPost.as_view() , name = 'postTweet'),
    url(r'^(?P<post_id>[0-9]+)/$', TweetDetail.as_view(), name='detailTweet'),
  
]

TweetApp/userapp/urls.py
"""TweetApp URL Configuration"""

from django.conf.urls import url , include
from django.contrib import admin
from .views import UserProfile
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

app_name = 'userapp'

urlpatterns = [
	url(r'^$', TemplateView.as_view(template_name = 'userapp/login.html') , name = 'home'),
	url(r'^login$', auth_views.login , {'template_name': 'userapp/login.html'} , name = 'userLogin'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'} , name='userLogout'),
    url(r'^userapp/profile$', UserProfile.as_view() , name = 'userProfile'),
    
    
]

TweetApp/commentapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from postapp.models import Post

# Create your models here.

class Comment(models.Model):

	comment_id = models.AutoField(primary_key = True)
	comment_text = models.CharField(max_length = 200)
	comment_datetime = models.DateTimeField(auto_now = True , auto_now_add = False)
	comment_user = models.ForeignKey(User , on_delete = models.CASCADE)
	comment_post = models.ForeignKey(Post , on_delete = models.CASCADE)

	def __str__(self):
		return self.comment_text

TweetApp/postapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Post(models.Model):

	post_id = models.AutoField(primary_key = True)
	post_text = models.TextField()
	post_date = models.DateField(auto_now = True , auto_now_add = False)
	post_time = models.TimeField(auto_now = True , auto_now_add = False)
	post_likes_count = models.IntegerField(default = 0)
	post_comments_count = models.IntegerField(default = 0)
	post_dislikes_count = models.IntegerField(default = 0)
	post_user = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.post_text



		




	

TweetApp/userapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

TweetApp/commentapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging
from django.views.generic import ListView
from django.contrib.auth import authenticate
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Comment

# Create your views here.

dblog = logging.getLogger(__name__)

@method_decorator(login_required, name = 'dispatch')
class ListCommentByUser(ListView):

	""" View the list of user comments"""

	template_name = 'commentapp/index.html'
	context_object_name = 'comment_list'


	def get_queryset(self):
		return Comment.objects.filter(comment_user  = self.request.user)


# @login_required
# def postComment(request):
# 	""" View the user comments"""
# 	u = request.user
# 	comment_list = Comment.objects.filter(comment_user  = u)
# 	dblog.info('postComment')
# 	context = { 'user' : u , 'comment_list' : comment_list}
# 	return render(request,'commentapp/index.html',context)
		
	
	

TweetApp/postapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, RedirectView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.dispatch import receiver
import logging

from postapp.models import Post
from commentapp.models import Comment
from postapp.signals import new_post

dblog = logging.getLogger(__name__)

@method_decorator(login_required, name = 'dispatch')
class TweetList(ListView):

	""" Display the user and friends' tweets"""

	model = Post
	template_name = 'postapp/index.html'
	
	def get_context_data(self):
		u = self.request.user
		dblog.info('showTweet')
		context = super(TweetList,self).get_context_data()
		user_post_list = Post.objects.filter(post_user = u)
		friends_post_list = Post.objects.exclude(post_user = u)
		context = { 'user' : u , 'user_post_list' : user_post_list  , 'friends_post_list' : friends_post_list}
		return context

@method_decorator(login_required, name = 'dispatch')
class TweetDetail(DetailView):

	""" Display the tweets' details"""
	model = Post
	template_name = 'postapp/detail.html'
	pk_url_kwarg = 'post_id'
	
	def get_context_data(self, **kwargs):
		dblog.info('detailTweet ')
		id = kwargs['object'].post_id
		context = super(TweetDetail,self).get_context_data(**kwargs)
		post = Post.objects.get(post_id = id)
		comments = Comment.objects.filter(comment_post__post_id = id)
		context = { 'post' : post , 'comments' : comments}
		return context

@method_decorator(login_required, name = 'dispatch')
class TweetPost(RedirectView):

	"""  Send mail as User posts something """

	pattern_name = 'postapp:showTweet'

	def get_redirect_url(self, *args, **kwargs):
		dblog.info('postTweet')
		u = self.request.user
		text = self.request.POST['text']
		if text:
			post = Post(post_text = text , post_user = u)
			post.save()
			new_post.connect(self.send_notification_mail)
			new_post.send(sender=Post, sig_post=post)
			url = super(TweetPost, self).get_redirect_url(*args, **kwargs) 
			return url

	@method_decorator(receiver(new_post) , name = 'dispatch')
	def send_notification_mail(self, sender, sig_post, **kwargs):
			
		dblog.info('notification receiver')
		str1 =  str(sig_post.post_text) + str(sig_post.post_user)
		user = User.objects.get(username = str(sig_post.post_user))
		subject = 'new post'
		message = str(sig_post.post_text) 
		sender =  'shalgitunix@gmail.com'
		recepient_list = []
		recepient_list.append(str(user.email)) 
		send_mail(subject, message, sender, recepient_list)




			
		
	

TweetApp/userapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging
from django.db.models import Count,Sum
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from postapp.models import Post


dblog = logging.getLogger(__name__)

@method_decorator(login_required , name = 'dispatch')
class UserProfile(TemplateView):

	template_name = 'userapp/profile.html'		
#	context_object_name = 'user_profile_details'

	def get_context_data(self):
		context = super(UserProfile,self).get_context_data()

		u = self.request.user   
		dblog.info('userProfile')  
		likes = Post.objects.filter(post_user = u).aggregate(Sum('post_likes_count'))
		dislikes = Post.objects.filter(post_user = u).aggregate(Sum('post_dislikes_count'))
		context['name'] = u.get_username()
		context['fullname'] = u.get_full_name()
		context['total_user_posts'] = Post.objects.filter(post_user = u).count()
		context['total_user_likes'] = likes['post_likes_count__sum']
		context['total_user_dislikes'] = dislikes['post_dislikes_count__sum']
		return context
	

TweetApp/commentapp/templates/commentapp/index.html
{% extends 'base.html' %}

{% block title_block %} UserProfile {% endblock%}

{% block heading_block %} <h1> Comments </h1> {% endblock%}

{% block content_block %} 

    <div class="container">
                {% if comment_list %}
                <ul>
                    {% for c in comment_list %}
                        <li>{{ c.comment_text }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                    <p>No comments are available.</p>
                {% endif %}
    </div>

{% endblock %}

TweetApp/postapp/templates/postapp/detail.html
{% extends 'base.html' %}

{% block title_block %} Tweets {% endblock%}

{% block heading_block %} <h1> Wanna share some thoughts </h1> {% endblock%}

{% block content_block %}

    <form>
          {% csrf_token %}
          <br>
          <div class="container">
            {% if post %}
                
                Post : <input type="text" name="post_text" value="{{ post.post_text }}" readonly><br>
                Date : <input type="text" name="post_date" value="{{ post.post_date }}" readonly><br>
                By   : <input type="text" name="post_user" value="{{ post.post_user }}" readonly><br>
                Likes : <input type="text" name="post_likes" value="{{ post.post_likes_count }}" readonly><br>
                Dislikes : <input type="text" name="post_dislikes" value="{{ post.post_dislikes_count }}" readonly><br>
                <br>
                Comments : 
                {% if comments %}
                <br>
                <ul>
                {% for c in comments %}
                    <li>{{ c.comment_text }}</a></li>
                {% endfor %}
                </ul>
                {% else %}
                    <p>No comments are available.</p>
                {% endif %}

            {% else %}
                <p>Post not available.</p>
            {% endif %}
          </div>
    </form>

{% endblock %}

TweetApp/postapp/templates/postapp/index.html
{% extends 'base.html' %}

{% block title_block %} Post {% endblock%}

{% block heading_block %} <h1> Share </h1> {% endblock%}

{% block content_block %} 

    <form action="{% url 'postapp:postTweet' %}" method="post">
      {% csrf_token %}

      <div class="container">
        <textarea rows="4" cols="80" name="text" id="text"> </textarea>
        <button type="submit" value="post"> Post </button>
      </div>
    </form>
      <br>
    <form>
      {% csrf_token %}
      <br>
      <div class="container">
        {% if friends_post_list %}
            <ul>
            {% for p in friends_post_list %}
                <li><a href="{% url 'postapp:detailTweet' p.post_id %}">{{ p.post_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>Your friends havn't posted anything</p>
        {% endif %}
      </div>
    </form>

{% endblock %}

{% block side_block %} 
    <h3> My Posts </h3>
    <form>
      {% csrf_token %}
      <div class="container">
        {% if user_post_list %}
            <ul>
            {% for p in user_post_list %}
                <li><a href="{% url 'postapp:detailTweet' p.post_id %}">{{ p.post_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No posts are available.</p>
        {% endif %}
      </div>
    </form>

{% endblock %}

TweetApp/templates/base.html
{% load static %}

<!doctype html>
<title>
  {% block title_block %} {% endblock %}
</title>
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</style> -->
<body>
  <header>
    {% block heading_block %} {% endblock %}
  </header>
  <div id="main">
    <article>
      {% block content_block %} {% endblock %}
    </article>
    <nav>
      <div id='menu'>
      <ul>
      <li>
      <a class="page-scroll" href="{% url 'postapp:showTweet' %}">Home</a>
      </li>
      <li>
      <a class="page-scroll" href="{% url 'userapp:userProfile' %}">Profile</a>
      </li>
      <li>
      <a class="page-scroll" href="{% url 'commentapp:postComment' %}">Comments</a>
      </li>
      <li>
        {% if user.is_authenticated %}
        <a class="page-scroll" href="{% url 'userapp:userLogout' %}">Logout</a>
        {% else %}
        <a class="page-scroll" href="{% url 'userapp:home' %}">Login</a>
        {% endif %}
      </li>
      <li>
      <a class="page-scroll" href="{% url 'userapp:userProfile' %}">Contact</a>
      </li>
    </ul>
  </div>
    </nav>
    <aside>
        {% block side_block %} {% endblock %}
    </aside>
  </div>
  <footer></footer>
</body>

TweetApp/userapp/templates/userapp/login.html
<html style="background: yellowgreen;font-family: sans-serif;font-size: large;"><head>
</head>

<body>
<h1 style="text-align: center" >Welcome Tweeters </h1>
<br>
<br>
<br>
<br>
<form action="{% url 'userapp:userLogin' %}" method="post" style="max-width: 360px;margin: 0 auto 100px; padding: 25px; font-family: &quot;Roboto&quot;, sans-serif;outline: 0;background: #f2f2f2;width: 100%;border: 0;;font-size: 14px;border-radius: 25px">
{% csrf_token %}
<br>
<br>
	<div class="container">
    	<label><b>Username</b></label>
    	<input placeholder="Enter Username" id="uname" name="username" required="" type="text">
    	<br>
	    <label><b>Password</b></label>
	    <input placeholder="Enter Password" id="psw" name="password" required="" type="password">
	    <br>
	    <br>
	    <button type="submit" value="Vote">Login</button>
	    <input checked="checked" type="checkbox"> Remember me
	</div>
<!--	<br>
	<div class="container">
	    <button type="button" class="cancelbtn">Cancel</button>
	    <span class="psw">Forgot <a href="#">password?</a></span>
	</div> -->

</form>


</body></html>

TweetApp/userapp/templates/userapp/profile.html
{% extends 'base.html' %}

{% block title_block %} UserProfile {% endblock%}

{% block heading_block %} <h1 style="text-align: center" >Welcome {{user}} </h1> {% endblock%}

{% block content_block %} 
  <form >
      {% csrf_token %}
      <br>
      <br>
      <div class="container">
        <table>
          <tr>
              <td><label><b>Name</b></label></td>
              <td><input id="uname" name="uname" type="text" value="{{ fullname }}" readonly></td>
          </tr>
          <tr>
              <td><label><b>Total Posts</b></label></td>
              <td><input id="posts" name="posts" type="text" value="{{ total_user_posts }}" readonly></td>
          </tr>
          <tr>
              <td><label><b>Total Likes</b></label></td>
              <td><input id="likes" name="likes" type="text" value="{{ total_user_likes }}" readonly></td>
          </tr>
          <tr>
              <td><label><b>Total Dislikes</b></label></td>
              <td><input id="dislikes" name="dislikes" type="text" value="{{ total_user_dislikes }}" readonly></td>
          </tr>
          <tr>
              <td><label><b>Joined on</b></label></td>
              <td><input id="joindate" name="joindate" type="text" value="{{ fullname }}" readonly></td>
          </tr>
        </table>
      </div>

      </form>

{% endblock %}